### ISSUE TITLE
Security Issue: default stream key?

### ISSUE THREAD

**Issue by Jonn3y** [GRVYDEV/Project-Lightspeed#19]
Hey,

i'm not sure if i do understand that right, but if the stream key has a default value (in this case `123456789-aBcDeFgHiJkLmNoPqRsTuVwXyZ123456`),
 wouldn't it be a security issue if it is not changed before hosting Lightspeed?

I mean, if i would know some IPs that are running your software, i could easiely use the default key just to try to connect?

Maybe a random generated key (or one handled by a docker environment label) would be better?

**Comment by GRVYDEV** [comment]
> Hey,
> 
> i'm not sure if i do understand that right, but if the stream key has a default value,
> wouldn't it be a security issue if it is not changed before hosting Lightspeed?
> 
> I mean, if i would know some IPs that are running your software, i could easiely use the default key just to try to connect?
> 
> Maybe a random generated key (or one handled by a docker environment label) would be better?

You're correct! A default stream key IS a security issue however I am aware of that and a better system is coming soon (see [this](https://github.com/GRVYDEV/Lightspeed-ingest/issues/11)) In the meantime someone can edit [this](https://github.com/GRVYDEV/Lightspeed-ingest/blob/b341115f69671b27820848267db95059af38b95c/src/connection.rs#L243) line in order to get around that!

**Comment by GRVYDEV** [comment]
Closing this as it has been remedied by [this](https://github.com/GRVYDEV/Lightspeed-ingest/pull/24) commit!
